# Generated by Django 4.2.4 on 2023-09-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('video', models.FileField(upload_to='movies')),
                ('length', models.IntegerField(max_length=4)),
                ('genre', models.CharField(choices=[('horror', 'HORROR'), ('drama', 'DRAMA'), ('fantasy', 'FANTASY'), ('action', 'ACTION'), ('science fiction', 'SCIENCE FICTION'), ('drama', 'DRAMA'), ('thriller', 'THRILLER'), ('western', 'WESTERN'), ('comedy', 'COMEDY')], max_length=20)),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
