# Generated by Django 4.2.4 on 2023-09-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_film_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='video',
            new_name='movie',
        ),
        migrations.AlterField(
            model_name='film',
            name='length',
            field=models.IntegerField(),
        ),
    ]
