# Generated by Django 4.2.4 on 2023-09-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_video_film_movie_alter_film_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie',
            field=models.FileField(upload_to='movies/%y'),
        ),
    ]
